#
# momo config
#
# renew from serverConfig.js
#
#
#
#
#


#
# mongodb info
#
mongodb: 
  url: mongodb://192.168.10.132
  port: 27017
  db: myMemo
  collection:
    simple: text
    pgmemo: pgmemo
#
# pg memo labels
#
# date
# title
# type [python, node, angularjs, reactjs, javascript, html, css, bootstrap, c]
# platform [win10, windows, ubuntu18, ubuntu, linux, mac, pic, embeded]
# text
#
pgmemo :
  type :
    - python
    - node
    - angularjs
    - reactjs
    - javascript
    - bootstrap
    - html
    - css
    - c
  platform :
    - win10
    - windows
    - ubuntu18
    - ubuntu
    - linux
    - mac
    - pic
    - embedded
  recentMemoNum :
    20