mongodb:
  url: 'mongodb://192.168.10.132'
  port: 27017
  db: myMemo
  collection:
    simple: text
    pgmemo: pgmemo
pgmemo:
  type:
    - python
    - node
    - angularjs
    - reactjs
    - javascript
    - bootstrap
    - html
    - css
    - c
  platform:
    - win10
    - windows
    - ubuntu18
    - ubuntu
    - linux
    - mac
    - pic
    - embedded
  recentMemoNum: 20
